data = {
    "page": "1",
    "total": "8",
    "registros": [
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319259",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2023-07-11",
            "valor": "75.00",
            "obs": "de 10/08/2023 até 10/09/2023",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "5",
            "documento": "183097",
            "id_saida": "183097",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "5",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192359020453904194700000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        },
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319260",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2023-10-10",
            "valor": "75.00",
            "obs": "de 10/09/2023 até 09/10/2023",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "6",
            "documento": "183098",
            "id_saida": "183098",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "6",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192360020453902194990000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        },
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319261",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2023-11-10",
            "valor": "75.00",
            "obs": "de 10/10/2023 até 09/11/2023",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "7",
            "documento": "183099",
            "id_saida": "183099",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "7",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192361020453900795300000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        },
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319262",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2023-12-11",
            "valor": "75.00",
            "obs": "de 10/11/2023 até 10/12/2023",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "8",
            "documento": "183100",
            "id_saida": "183100",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "8",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192362020453908495610000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        },
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319263",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2024-01-10",
            "valor": "75.00",
            "obs": "de 10/12/2023 até 09/01/2024",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "9",
            "documento": "183101",
            "id_saida": "183101",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "9",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192363020453906695910000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        },
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319264",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2024-02-12",
            "valor": "75.00",
            "obs": "de 10/01/2024 até 11/02/2024",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "10",
            "documento": "183102",
            "id_saida": "183102",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "10",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192364020453904296240000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        },
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319265",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2024-03-11",
            "valor": "75.00",
            "obs": "de 10/02/2024 até 10/03/2024",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "11",
            "documento": "183103",
            "id_saida": "183103",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "11",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192365020453901396520000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        },
        {
            "id_remessa": "0",
            "gateway_link": "",
            "nn_boleto": "",
            "boleto": "",
            "data_inicial": "0000-00-00",
            "data_final": "0000-00-00",
            "id": "319266",
            "liberado": "S",
            "filial_id": "1",
            "status": "A",
            "data_emissao": "2023-04-10",
            "data_vencimento": "2024-04-10",
            "valor": "75.00",
            "obs": "de 10/03/2024 até 09/04/2024",
            "valor_recebido": "0.00",
            "valor_aberto": "75.00",
            "id_cliente": "5519",
            "pagamento_valor": "",
            "pagamento_data": "",
            "id_carteira_cobranca": "3",
            "credito_data": "",
            "baixa_data": "",
            "numero_parcela_recorrente": "12",
            "documento": "183104",
            "id_saida": "183104",
            "tipo_recebimento": "Boleto",
            "tipo_renegociacao": "",
            "valor_cancelado": "0.00",
            "data_cancelamento": "",
            "id_mot_cancelamento": "",
            "id_renegociacao": "",
            "id_cobranca": "",
            "previsao": "S",
            "id_renegociacao_novo": "",
            "libera_periodo": "N",
            "impresso": "S",
            "forma_recebimento": "",
            "arquivo_remessa_baixado": "",
            "nparcela": "12",
            "id_nota_gerada_opc4": "",
            "status_cobranca": "",
            "tipo_cobranca": "E",
            "id_contrato_principal": "0",
            "id_contrato_avulso": "",
            "id_contrato": "10622",
            "id_nota_gerada": "0",
            "id_im_imovel": "",
            "parcela_proporcional": "N",
            "linha_digitavel": "23791425049000003192366020453909596820000007500",
            "duplicata": "",
            "tipo_pagamento_cartao": "",
            "id_sip": "",
            "titulo_protestado": "N",
            "desconto_condicional_valor": "",
            "gerencianet_token": "",
            "validade_desconto_condicional": "",
            "id_conta": "174",
            "motivo_alteracao": "",
            "id_remessa_alteracao": "",
            "cancelamento_id_operador": "",
            "baixa_id_operador": "",
            "titulo_importado": "N",
            "origem_importacao": "",
            "ultima_atualizacao": "2023-04-10 16:19:31",
            "aguardando_confirmacao_pagamento": "N",
            "parcelado_cartao": "N",
            "pix_txid": "",
            "id_nota_gerada_opc2": "",
            "id_nota_gerada_opc3": "",
            "recebido_via_pix": "N"
        }
    ]
}

// console.log(data.registros)

data = JSON.parse(data)

dataAlterada = data.registros.map((e) => {
    dataEmTraco = e.data_vencimento.split("-")
    e.data_vencimento = dataEmTraco[2] + "/" + dataEmTraco[1] + "/" + dataEmTraco[0]

    const date = new Date();

    mes = date.getMonth() + 1;
    ano = date.getFullYear

    inicio = "01/"+ mes + "/"+ano

    const aVencer = [e].filter((dado) => {
        if (inicio < e.data_vencimento) {
    
        return dado
    
        } else {
            return "erro"
        }
    })
    

    return aVencer
})


